"""Normalized owner-scoped Ads and Marketing Automation domain."""

from vayujit_api.ads.models import (
    Ad,
    AdAccount,
    AdAudience,
    AdBidRecommendation,
    AdBudget,
    AdBudgetRecommendation,
    AdCampaign,
    AdConversion,
    AdCreative,
    AdCreativeFatigueSignal,
    AdExperiment,
    AdExperimentResult,
    AdExperimentVariant,
    AdGroup,
    AdJob,
    AdMetric,
    AdOptimizationDecision,
    AdOptimizationExecution,
    AdOptimizationRecommendation,
    AdOptimizationRule,
    AdPerformanceAnomaly,
    AdRemoteMapping,
    AdSchedule,
    AdSet,
)

__all__ = [
    "Ad",
    "AdAccount",
    "AdAudience",
    "AdBudget",
    "AdCampaign",
    "AdConversion",
    "AdCreative",
    "AdExperiment",
    "AdExperimentResult",
    "AdExperimentVariant",
    "AdBidRecommendation",
    "AdBudgetRecommendation",
    "AdCreativeFatigueSignal",
    "AdOptimizationDecision",
    "AdOptimizationExecution",
    "AdOptimizationRecommendation",
    "AdPerformanceAnomaly",
    "AdGroup",
    "AdSet",
    "AdJob",
    "AdMetric",
    "AdOptimizationRule",
    "AdRemoteMapping",
    "AdSchedule",
]
